apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 5
  minReadySeconds: 10
  selector:
    matchLabels:
      role: vote
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote:v1
          ports:
            - containerPort: 80
              protocol: TCP








    # resources:
    #   requests:
    #     memory: "100Mi"
    #     cpu: "100m"   # Request for 0.1 CPU cores
    #   limits:
    #     memory: "200Mi"
    #     cpu: "500m"   # Limit for 0.5 CPU cores
