# apiVersion: v1
# kind: Service
# metadata:
#   name: vote
#   namespace: instavote
#   labels:
#     role: vote
# spec:
#   selector:
#     role: vote
#     version: v1
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30000
#   type: NodePort
#   externalIps:
#     - 192.168.58.2
#     - 172.21.153.111

---
# Used for loadbalancing type port. Works with minikube tunnel 

apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: instavote
  labels:
    role: vote
spec:
  selector:
    role: vote
    version: v1
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000
  type: LoadBalancer
